name: Release Please

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-stable:
    name: Stable release
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@0dfd8538845b8e92600d271a895a5372865d4062 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          config-file: release-please-config.stable.json
          manifest-file: .release-please-manifest.stable.json

  release-beta:
    name: Beta prerelease
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@0dfd8538845b8e92600d271a895a5372865d4062 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: develop
          config-file: release-please-config.beta.json
          manifest-file: .release-please-manifest.beta.json
